[package]
name = "roguelike-game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "roguelike_game"
path = "src/main.rs"

[lib]
name = "roguelike_game"
path = "src/lib/mod.rs"

[dependencies]
rltk = "0.8.0"
specs = "0.16.1"
specs-derive = "0.4.1"